### ISSUE TITLE
requirements.txt doesn't work

### ISSUE THREAD

**Issue by jeffreyouni** [ohyicong/decrypt-chrome-passwords#12]
Could not find a version that satisfies the requirement sqlite (from versions: none)

**Comment by jeffreyouni** [comment]
change back to this version and working perfect now.
[https://github.com/ohyicong/decrypt-chrome-passwords/commit/4d2c2aec757dfd9011dbacf02c0a820594904ca7](https://github.com/ohyicong/decrypt-chrome-passwords/commit/4d2c2aec757dfd9011dbacf02c0a820594904ca7)

**Comment by ohyicong** [comment]
Hi, thanks for highlighting I have added the versions into the requirement file to ensure compatibility.
