### ISSUE TITLE
No module named win32crypt

### ISSUE THREAD

**Issue by hegehog8761** [ohyicong/decrypt-chrome-passwords#14]
Running the main file returns that the win32crypt module has not been installed, `pip install win32crypt` returns that there is no known win32 distribution, using the requirements.txt throws an error that `= is not a valid operator` and changing to `==` returns that there are no matching distributions for sqlite

**Comment by p01terge1st** [comment]
same problem.

**Comment by wendellmeset** [comment]
same

**Comment by ji4a** [comment]
Try: `pip install pypiwin32`

**Comment by hegehog8761** [comment]
> Try: `pip install pypiwin32` @hegehog8761 @p01terge1st @wendellmeset 

Thanks, I also had to replace Cryptodome with pycryptodome to get it to work but wouldn't have been able to it without this help
