### ISSUE TITLE
PIP Install (Py2 && Py3)

### ISSUE THREAD

**Issue by KazutoKashima** [ohyicong/decrypt-chrome-passwords#4]
## Description:
Having originally attempted to write my own version of this in Node.JS, I decided to write the actual decryption using this repo.
Unfortunately I've come across a pip issue that is ultimately the same using python 2 and python 3 as well, saying the following:
```py
# using py2 with slight requirements modification
pip2 install -r requirements.txt                                                                                                                     
ERROR: Invalid requirement: u'alabaster=0.7.12' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

# using py3 with a straight copy from the repo requirements file
pip3 install -r requirements.txt                                                                                                                       
ERROR: Invalid requirement: 'alabaster=0.7.12=pyhd3eb1b0_0' (from line 5 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
```

## System 
OS: Debian 10
PIP version: 20.3.4 (python 3.9/2.7)

#### Note:
I haven't done much in python for a while now, but I'm assuming that getting versions with PIP uses `==` instead of `=` as the Hint indicates

**Comment by alessio-ds** [comment]
I've sent a pull request to fix this problem.

For now, delete every line from `requirements.txt `and paste this instead:

sqlite
pycryptodomex
csv
pywin32
