### ISSUE TITLE
Passwords blank in CSV

### ISSUE THREAD

**Issue by LU5GOON** [ohyicong/decrypt-chrome-passwords#8]
Hello @ohyicong  

Great work on this, huge fan of what's applied here and how you explained it. The script runs great, generates the CSV but the password field is blank.

If I run it via cmd to get the print out, I have a stack of utf-8 codec errors. Chrome is on the latest version and I am using Python 3.10.5

Edit: I forgot to mention the LoginData file was lifted from another machine entirely. I assume maybe it's looking for the machine ID of where it came from. Any way I can edit that to focus on my machine? 

![image](https://user-images.githubusercontent.com/100285625/177693899-9dd975d3-d02f-4394-8577-68393122329b.jpeg)

Any pointers as to why this would be printing the url and usernames but not the passwords? 

Thank you

**Comment by ohyicong** [comment]
Hi i couldn't replicate the issue

**Comment by ohyicong** [comment]
I have this suggestion from stackoverflow:
Replace:
 open('decrypted_password.csv', mode='w', newline='', encoding='utf-8')
With:
 open('decrypted_password.csv', mode='w', newline='', encoding='ISO-8859-1')

**Comment by LU5GOON** [comment]
> I have this suggestion from stackoverflow:
> 
> Replace:
> 
>  open('decrypted_password.csv', mode='w', newline='', encoding='utf-8')
> 
> With:
> 
>  open('decrypted_password.csv', mode='w', newline='', encoding='ISO-8859-1')


Hello @ohyicong 

Thank you for sending this through. I still am getting blank password fields but all other data seems to be ok. 

Since the line change, result remains the same with UTF-8 still being referenced in the error as well as the version of chrome? The file I know came from an updated chrome browser. 

Images supplied below for reference. 

I am really confused here... 

![image](https://user-images.githubusercontent.com/100285625/177886730-1bf0fc9e-cefa-48d6-a1d7-612547bf6d3f.png)

![image](https://user-images.githubusercontent.com/100285625/177886748-34a3a54f-8889-48ef-b176-6f44111dfa1e.png)

**Comment by LU5GOON** [comment]
After reading numerous forums. I think my issue is due to the Login Data file being from a total different machine. I managed to obtain it from a target.

Can you please confirm you cannot action this if the Login Data file is from another machine? 

Thank you @ohyicong

**Comment by ohyicong** [comment]
Hi, it doesn't work if you copied from other computer.
