### ISSUE TITLE
Not grabbing all passwords / none

### ISSUE THREAD

**Issue by rjceledon** [ohyicong/decrypt-chrome-passwords#9]
I was testing for a deployment and the script wasn't grabbing the only password I had stored, after debugging found that this line was causing issues, as the result of "url" variable was empty for my case, only username and ciphertext were filled. I created this password in Chrome by adding it manually.

Line 87:
```python
if(url!="" and username!="" and ciphertext!=""):
```

Had to replace it as:
```python
if(ciphertext!=""):
```

And it worked like a charm, thanks!

**Comment by syzdeek** [comment]
I have the same problem..
Also replaced it like @rjceledon but in output it didn't show the url.
![obraz](https://user-images.githubusercontent.com/101279459/204388965-dd155f24-6da2-4b60-8198-843567aa8db6.png)

**Comment by ohyicong** [comment]
Hi, this is not an issue. It is my intended logic as it doesn't make sense to decrypt the password if chrome didn't save its url link. Thanks for the feedback.
